---
abstract: 'semantic cryptography'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
keywords:
  - RDF
  - Cryptography
  - RSA
  - WebID
  - 'Semantic Web'
  - Graph
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Crypt
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::OpenSSL::Bignum: 0
  Crypt::OpenSSL::RSA: 0
  Crypt::OpenSSL::Random: 0
  Digest::SHA1: 0
  File::Slurp: 0
  MIME::Base64: 0
  Mail::Message: 0
  Mail::Transport::SMTP: 0
  Mail::Transport::Send: 0
  Mail::Transport::Sendmail: 0
  RDF::RDFa::Parser: 0
  RDF::TrineShortcuts: 0
  Scalar::Util: 0
  Sys::Hostname: 0
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Crypt
  homepage: http://search.cpan.org/dist/RDF-Crypt/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/RDF-Crypt/
version: 0.001
