---
abstract: 'semantic cryptography'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - Cryptography
  - Graph
  - RDF
  - RSA
  - SemWeb
  - 'Semantic Web'
  - WebID
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::Crypt
name: RDF-Crypt
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.16
  Crypt::OpenSSL::Bignum: 0.04
  Crypt::OpenSSL::RSA: 0.24
  File::Slurp: 9999
  Mail::Message: 2.100
  RDF::Query: 2.900
  RDF::RDFa::Parser: 1.097
  RDF::TrineX::Functions: 0.001
  Web::ID: 1.900
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-Crypt
  homepage: https://metacpan.org/release/RDF-Crypt
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-crypt
version: 0.002
